### PR TITLE
Recovery

### PR DESCRIPTION
**Pull request by ruvdrsti**
Some data was lost while pushing from the HPC. This branch is made to recover said data, and clean it up a bit too.

### CODE REVIEW

**Comment by ruvdrsti** [comment]
this is what I have for the implementation, but it is far from finished. The main idea is to get UHF fock matrices and then replace the cv and vc blocks by the ones from a closed shell type operator. This operator is obtained by adding eqs 16a and 16b from the paper by Scuseria.

**Review by johdvos — COMMENTED** [review]
I had a look at the code you have so far. Try doing the following: Make a UHF iteration function and identify where the CUHF algorithm differs. At that point (it is in fact only 1 points) introduce a function that will impose the constraint. You guys seem to understand what the constraint entails, but the transformations are off. Try to really see which matrices are needed to impose the constraint. If you wish we can have a chat about this in the upcoming week.

**Comment by ruvdrsti** [comment]
Might be a good idea, since I'm having a little difficulty translating the theory into code.

**Comment by ruvdrsti** [comment]
At this stage, I changed an option in the `psi4.set_options()` command. Using `{"scf_type": "pk"} got me closer to the reference data from psi4. However, the allyl radical is not working correctly yet.

**Comment by johdvos** [comment]
> At this stage, I changed an option in the `psi4.set_options()` command. Using `{"scf_type": "pk"} got me closer to the reference data from psi4. However, the allyl radical is not working correctly yet. The CUHF code should be working better now.

Try using mixed guess for the allyl radical.

**Pull request merged**
